### ISSUE TITLE
All programs fail to compile with serial lib in nim 1.0

### ISSUE THREAD

**Issue by accaldwell** [euantorano/serial.nim#22]
All programs are failing to compile with nim 1.0.0 with the following error:

`/home/snip/.nimble/pkgs/serial-1.1.2/serial/serialstream.nim(117, 17) Error: type mismatch: got <proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe, locks: <unknown>.}> but expected 'proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.}'
.raise effects differ`

The only thing needed to trigger this error on compilation is a one line test file:

`import serial`

**Comment by euantorano** [comment]
Thanks for the report, I’ll have a look after work tonight and push a patch.

**Comment by euantorano** [comment]
I've just tested this and I can't reproduce the issue on `Nim Compiler Version 1.0.0 [MacOSX: amd64]`. Can you post the output of `nim -v` so I can see what platform you're on?

I have found another issue that affects compatibility with v1.0.0 though.

**Comment by accaldwell** [comment]
`Nim Compiler Version 1.0.0 [Linux: amd64]
Compiled at 2019-09-23
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f7a8fc46c0012033917582eb740dc0343c093e35
active boot switches: -d:release`

Installed using choosenim on Arch Linux.

**Comment by euantorano** [comment]
Thanks, I’ll need to test on a Linux system. You should be able to `import serial/serialport` for now hopefully.

**Comment by accaldwell** [comment]
Yeah, unfortunately the code I'm writing uses serial/utils and serial/serialstream also.

FYI, this seems broken as far back as 0.20.0, but 0.19.6 works fine on my test machines.

**Comment by euantorano** [comment]
I’m. I think I had a report about it before but couldn’t reproduce it then either. I’ll set up a Linux machine and test today. By any chance are you using —threads:on or anything?

**Comment by accaldwell** [comment]
Hmm, actually it looks like this was fixed as part of #21. I was testing with version 1.1.2 as installed by nimble (the latest release version), which didn't include that fix. `nimble install serial@#head` installs a version that works.

**Comment by euantorano** [comment]
I’ll create a new release today and see if that helps nimble.

**Comment by PMunch** [comment]
I ran into the same issue today, also with 1.1.2. Did you create a new release?

**Comment by euantorano** [comment]
@PMunch 1.1.3 [was released recently](https://github.com/euantorano/serial.nim/commit/a6fb5bb9fea975e8229b5ace4ba8c3f33402545f). There have been a few changes since then, and I'm planning to tag a new release once I fix #25 and #26.

**Comment by PMunch** [comment]
Ah, you forgot to tag that release with a git tag which is what I believe nimble uses to get versions. So it installs 1.1.2 by default.

**Comment by euantorano** [comment]
Yep, seems like it. I'm sure Nimble used to just use the `.nimble` file, but I know you have to try and keep the 2 in sync which is a bit of a pain.
